version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: "rt_db"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/
  web:
    build: ./web
    container_name: "rt_web"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/app_name
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    